language: node_js
os:
  - linux
dist: xenial
cache:
  directories:
    - node_modules
    - ~/.npm
# last version of node
node_js:
  - '12'
# depth on branches
git:
  depth: 3
# like npm run build comand
deploy:
# like heroku, but is github-pages
  provider: pages
  strategy: git
  # to clean up
  skip_cleanup: true
  keep_history: true
  # to connect with github
  token: $GITHUB_TOKEN
  # path where all will be store, dir resoult of compilation
  local_dir: dist/ # as public o bundle
  # this branch it recomended of Github
  target_branch: gh-pages
  commit_message: "Deploying project"
  on:
    branch: main
